sudo: required

language: node_js
node_js:
- '9'

services:
- docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

script:
  - npm install
  - npm test
  - docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .

deploy:
  provider: script
  script:
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on: master
